name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: Ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: change directory
      run: cd LiveTransferMarket.API/LiveTransferMarket.API
    - name: Build the Docker image
      run: 
            docker build . --file Dockerfile --tag ltmapi:$(date +%s)